homepage modal, stimulus add fishing trip
jweber13/Fishr pull request #9
Opened 2023-06-15 08:07 UTC by jweber13

2023-06-15 08:08 UTC, jweber13 commented
Merge Conflicts with controllers / index.js & Yarn.lock. 

Also, need to re-write the modal to close upon success. it will close with cancel, and 'submit' does add the name to the db & create a new fishing  trip.

2023-06-15 13:45 UTC, Donald-Chow requested changes
Clean up Javascript before pull

Index is a conflict in the controller, we should accept both
Yarn Lock conflict should be on versioning, suggest to keep base version of yarn lock when merge

2023-06-15 13:45 UTC, Donald-Chow commented on app/views/pages/home.html.erb
> +  <script>
Why are there Javascript in the ERB?!?!??!?!?!

2023-06-15 13:45 UTC, Donald-Chow commented on app/javascript/controllers/index.js
> +
This controller is no longer valid

! Remove

2023-06-15 13:45 UTC, Donald-Chow commented on app/policies/application_policy.rb
> +  include Devise::Controllers::Helpers
Are we still using Devise in Pundit?
If not, ! Remove

2023-06-15 13:45 UTC, Donald-Chow commented on app/views/pages/home.html.erb
> +  <script>
Looks like this is the DOM changes on click.
! move to stimulus controller

2023-06-19 07:22 UTC, Donald-Chow commented
@jweber13 I've made a bunch of changes to the stimulus controllers (both modalhandler and fishing-trip-input) and adjusted the syntax accordingly. In addition, I have made the modal a partial where we can render from anywhere.

**Please review**

Additional consideration, if we use simpleform, if the trip is created unsuccessfully, an alert will be created to tell the user why the trip is not created properly. if that is something we want to do. alternative/ additional, we can add flashes when the trip is created properly

2023-06-19 07:30 UTC, Donald-Chow commented
@jweber13 I just merged master and resolve conflict.

Please review

2023-06-20 05:45 UTC, Donald-Chow approved these changes

2023-06-20 05:46 UTC, merged